name: Daily Notifications

on:
  schedule:
    # Run at 9 AM UTC every day
    - cron: "0 9 * * *"
  # Allow manual trigger
  workflow_dispatch:

jobs:
  send-notifications:
    runs-on: ubuntu-latest

    steps:
      - name: Send daily notifications
        run: |
          curl -X POST ${{ secrets.APP_URL }}/api/send-daily-notification \
            -H "Authorization: Bearer ${{ secrets.GITHUB_ACTIONS_SECRET }}" \
            -H "Content-Type: application/json"
