name: Daily Notifications

on:
  schedule:
    # Run at 11 AM UTC every day
    - cron: "0 11 * * *"
  # Allow manual trigger
  workflow_dispatch:

jobs:
  send-notifications:
    name: Send Daily Notifications
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Send daily notifications
        run: |
          echo "Starting daily notifications job..."

          # Debug: Check if secret is set (without revealing the value)
          if [ -z "$ACTIONS_SECRET" ]; then
            echo "Error: ACTIONS_SECRET is not set"
            exit 1
          fi

          # Construct the Authorization header
          AUTH_HEADER="Authorization: Bearer $ACTIONS_SECRET"

          echo "Sending daily notification..."
          response=$(curl -s -w "\n%{http_code}" \
            -X POST https://drawcast.xyz/api/send-daily-notification \
            -H "$AUTH_HEADER" \
            -H "Content-Type: application/json" \
            --max-time 30 \
            --retry 3 \
            --retry-delay 5)

          # Split response into body and status code
          body=$(echo "$response" | head -n -1)
          status_code=$(echo "$response" | tail -n 1)

          echo "Response status code: $status_code"
          echo "Response body: $body"

          # Check if the request was successful
          if [ "$status_code" -eq 200 ]; then
            echo "Notifications sent successfully!"
            exit 0
          else
            echo "Failed to send notifications"
            exit 1
          fi
        env:
          ACTIONS_SECRET: ${{ secrets.ACTIONS_SECRET }}
